### ISSUE TITLE
?stats all doesnt work

### ISSUE THREAD

**Issue by MiTonder** [MiTonder/modmail-plugins#10]
**Describe the bug**
`?stats all` doesnt work

**To Reproduce**
1. Use the command `?stats all`
2. Observe that nothing happens

**Expected result**
The embed paginator session should start

**Actual result**
Nothing happens

**Additional comments**
I am working on this right now

**Comment by TheKinG2149** [comment]
Lol

**Comment by MiTonder** [comment]
@TheKinG2149 lol urself

**Comment by MiTonder** [comment]
Identified (Hopefully): Need to change the PaginatorSession to EmbedPaginatorSession

**Comment by MiTonder** [comment]
And import EmbedPaginatorSession

**Comment by MiTonder** [comment]
Fixed, simply update the bot and itll work
