### ISSUE TITLE
Members command issue

### ISSUE THREAD

**Issue by MiTonder** [MiTonder/modmail-plugins#21]
**Describe the bug**
With too many members in a role, the members command will not send an embed
**To Reproduce**
1. Use the `?members` command with a role that has many members
2. Observe 

**Expected result**
It should send an embed, maybe with paginators
**Actual result**
It doesn't send anything
**Additional comments**
I will try to work on it

**Comment by TheKinG2149** [comment]
Don't you find this weird. Lol

**Comment by MiTonder** [comment]
I do, nub me cant fix

**Comment by MiTonder** [comment]
Papier was OP and saved the day

**Comment by TheKinG2149** [comment]
🙀
