### ISSUE TITLE
You cant user user ID or mention in userinfo

### ISSUE THREAD

**Issue by MiTonder** [MiTonder/modmail-plugins#6]
I am gonna fix this later today maybe.

**Comment by MiTonder** [comment]
If im not wrong this should be done, right? ```    @staticmethod
    def get_member(ctx, name: discord.Member):
        """Get the member object from a (particial) name"""

        if name is None:
            return None

        for m in ctx.guild.members:
            if m.display_name.lower().startswith(name.lower()):
                return m
            elif m.name.lower().startswith(name.lower()):
                return m
            else:
                continue

        return None```

**Comment by kyb3r** [comment]
You shouldn't really do this, the member converter already takes care of converting to a member object.

**Comment by MiTonder** [comment]
But what should be done then?

**Comment by kyb3r** [comment]
Read the docs about converters in the commands extension

**Comment by MiTonder** [comment]
Finally Done, Thanks to Papiersnipper
